changed the .gitignore to include vscode C# extension build result service is available.   Determining projects to restore...   All projects are up-to-date for restore. c:\Users\tynuk\lab1-John-Bastille\lab1\JohnBastille\Task1\src\Program.cs(14,25): error CS1729: 'Group' does not contain a constructor that takes 0 arguments c:\Users\tynuk\lab1-John-Bastille\lab1\JohnBastille\Task1\src\Program.cs(14,32): error CS0200: Property or indexer 'Group.Name' cannot be assigned to -- it is read only c:\Users\tynuk\lab1-John-Bastille\lab1\JohnBastille\Task1\src\Program.cs(15,28): error CS0246: The type or namespace name 'Student' could not be found (are you missing a using directive or an assembly reference?) c:\Users\tynuk\lab1-John-Bastille\lab1\JohnBastille\Task1\src\Program.cs(15,13): error CS1061: 'Group' does not contain a definition for 'AddStudent' and no accessible extension method 'AddStudent' accepting a first argument of type 'Group' could be found (are you missing a using directive or an assembly reference?) c:\Users\tynuk\lab1-John-Bastille\lab1\JohnBastille\Task1\src\Program.cs(17,29): error CS0246: The type or namespace name 'Student' could not be found (are you missing a using directive or an assembly reference?) c:\Users\tynuk\lab1-John-Bastille\lab1\JohnBastille\Task1\src\Program.cs(17,13): error CS1061: 'Group' does not contain a definition for 'AddStudent' and no accessible extension method 'AddStudent' accepting a first argument of type 'Group' could be found (are you missing a using directive or an assembly reference?) c:\Users\tynuk\lab1-John-Bastille\lab1\JohnBastille\Task1\src\Program.cs(19,29): error CS0246: The type or namespace name 'Student' could not be found (are you missing a using directive or an assembly reference?) c:\Users\tynuk\lab1-John-Bastille\lab1\JohnBastille\Task1\src\Program.cs(19,13): error CS1061: 'Group' does not contain a definition for 'AddStudent' and no accessible extension method 'AddStudent' accepting a first argument of type 'Group' could be found (are you missing a using directive or an assembly reference?) c:\Users\tynuk\lab1-John-Bastille\lab1\JohnBastille\Task1\src\Program.cs(21,25): error CS1729: 'Group' does not contain a constructor that takes 0 arguments c:\Users\tynuk\lab1-John-Bastille\lab1\JohnBastille\Task1\src\Program.cs(21,32): error CS0200: Property or indexer 'Group.Name' cannot be assigned to -- it is read only c:\Users\tynuk\lab1-John-Bastille\lab1\JohnBastille\Task1\src\Program.cs(22,29): error CS0246: The type or namespace name 'Student' could not be found (are you missing a using directive or an assembly reference?) c:\Users\tynuk\lab1-John-Bastille\lab1\JohnBastille\Task1\src\Program.cs(22,14): error CS1061: 'Group' does not contain a definition for 'AddStudent' and no accessible extension method 'AddStudent' accepting a first argument of type 'Group' could be found (are you missing a using directive or an assembly reference?) c:\Users\tynuk\lab1-John-Bastille\lab1\JohnBastille\Task1\src\Program.cs(24,29): error CS0246: The type or namespace name 'Student' could not be found (are you missing a using directive or an assembly reference?) c:\Users\tynuk\lab1-John-Bastille\lab1\JohnBastille\Task1\src\Program.cs(24,14): error CS1061: 'Group' does not contain a definition for 'AddStudent' and no accessible extension method 'AddStudent' accepting a first argument of type 'Group' could be found (are you missing a using directive or an assembly reference?) c:\Users\tynuk\lab1-John-Bastille\lab1\JohnBastille\Task1\src\Program.cs(26,29): error CS0246: The type or namespace name 'Student' could not be found (are you missing a using directive or an assembly reference?) c:\Users\tynuk\lab1-John-Bastille\lab1\JohnBastille\Task1\src\Program.cs(26,14): error CS1061: 'Group' does not contain a definition for 'AddStudent' and no accessible extension method 'AddStudent' accepting a first argument of type 'Group' could be found (are you missing a using directive or an assembly reference?) Lines starting